version: "3"

services:
  docker-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: navi-backend
    container_name: navi-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "27017:27017"
    volumes:
      - /node_modules
